name: Selenium Test Suite

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Java 24
        uses: actions/setup-java@v4
        with:
          java-version: '24'
          distribution: 'temurin'
          cache: maven

      - name: Run Tests
        run: mvn test -Dsurefire.suiteXmlFiles=group-test.xml,parallel-test.xml,firstExercise.xml

      - name: Upload Report
        if: always()
        uses: actions/upload-artifact@v4  # Fixed the name here
        with:
          name: test-reports
          path: target/surefire-reports/